### ISSUE TITLE
Jira Keys are Case Sensitive

### ISSUE THREAD

**Issue by Eddie-Hartman** [microsoft/azure-pipelines-jira#14]
**Describe the bug**
When committing, the Jira issue key must be the same Capitalization. I don't know if Jira keys are case sensitive (this issue is assuming that they aren't), but it would be nice if when looking through commits it could case-insensitive.

In Jira, if you try to navigate to issue key abc123 it will redirect you to ABC123 so I assume it is not case sensitive.

**To Reproduce**
1. Create a commit with a Jira key such as abc123 in the commit message.
2. Release it in a pipeline.
3. Observe it does not appear in the Work Items section of the AzureDevops pipeline.

**Expected behavior**
Either an option to make it case insensitive, or at least a mention in the documentation that it is indeed case sensitive.

**Screenshots**
There is a commit "brmi-361" that does not pick up the Jira issue.
![image](https://user-images.githubusercontent.com/14089997/64222056-e002a300-ce9c-11e9-96d1-a40396bc0e63.png)
![image](https://user-images.githubusercontent.com/14089997/64222101-13ddc880-ce9d-11e9-8f7d-cf4fe2912680.png)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version AzureDevops Git Repo + AzureDevops Pipeline + Jira

**Comment by sefi-jwilliams** [comment]
+1

**Comment by Gustavmk** [comment]
+1

**Comment by Eddie-Hartman** [comment]
Closing this since this repo is no longer being maintained.
