### ISSUE TITLE
Development / Releases / Deployment tab not showing

### ISSUE THREAD

**Issue by kvansaders** [microsoft/azure-pipelines-jira#15]
I was able to add the Azure Pipelines for JIRA app to our instance and added the JIRA integrations in our release pipelines.  However, I do not see any of the integration features in the related tickets, even with the JIRA ticket number in the commit comments and branch names.

We are using git inside Azure DevOps, but care more about the release aspect at this point.

![image](https://user-images.githubusercontent.com/4818333/64431843-36343980-d089-11e9-99d3-7affdccbde9a.png)

**Comment by kvansaders** [comment]
It turns out that this needed to be added to the view by configuring the default view layout for issues.  This step should be added to the setup documentation.

**Comment by matthieugd** [comment]
Can you share an issue where the deployment status is displayed? I setup the integration and It seems to work(I see the JIRA issue in the release details) but I don’t see the deployment info on the JIRA side.

**Comment by juandows** [comment]
How add to the view?
![image](https://user-images.githubusercontent.com/7058648/81276943-fc6e6500-9053-11ea-8ffc-0ab38669b592.png)

**Comment by kvansaders** [comment]
Project Settings -> Issue Layout
Choose the issue type you wish to change.  Ex: my org has separate layouts for bugs vs everything else.

Look for "Releases Panel" and move it to the Context Fields in the visible column.

![image](https://user-images.githubusercontent.com/4818333/81325090-e073bf00-9065-11ea-96e0-a6813252cfa5.png)
