### ISSUE TITLE
Will this integration be available for Jira Cloud and/or Server? 

### ISSUE THREAD

**Issue by bremnes** [microsoft/azure-pipelines-jira#2]
Functionality-wise this seems like just what we need, and we are eagerly waiting for its release.

Looking at the similar [integration for Github](https://marketplace.atlassian.com/apps/1219592/github-for-jira?hosting=cloud&tab=reviews), it only support Jira Cloud. So what would be supported for the azure pipelines integration? Obviously we are hoping for Jira Server as well.

Thanks!

**Comment by oising** [comment]
Hell, yes. We tried JIRA cloud but their single instance multitenant model doesn't seem to do well performance wise at peak periods. We reverted to JIRA server, which has more features anyway. We need this for JIRA server.

**Comment by oising** [comment]
@bremnes I managed to contact Microsoft about this, and the timeline is about three weeks. Sadly, the release is aimed at JIRA cloud only (for the moment.)

**Comment by wi5nia** [comment]
Need this for Jira server!

**Comment by shashban** [comment]
@oising @wi5nia - Jira Server doesn't have the the deployments API needed to list releases in the development section. Would it be sufficient to be unidirectional - support listing issues in releases and not the other way round.
