### ISSUE TITLE
When will be available this integration?

### ISSUE THREAD

**Issue by dmoreno** [microsoft/azure-pipelines-jira#3]
Hi!

This integration will be very useful for us! When is it expected to arrive? any ETA?

Thanks for this work!

**Comment by jharris8567** [comment]
I was told 2 weeks ago, about 2 weeks. Below is the link on the Atlassian Market Place. The installation tab still says coming soon. 

https://marketplace.atlassian.com/apps/1220515/azure-pipelines-for-jira?hosting=cloud&tab=overview

**Comment by stephanonline** [comment]
Just had contact about this. 
> We are in the final process of the release and this is expected to be available in a week or so.

Hopefully this will be soon :)

**Comment by stephanonline** [comment]
Just released! It only seems that you cannot connect your git repositories that are in Azure DevOps.

**Comment by dmoreno** [comment]
Great!
