### ISSUE TITLE
Update on JIRA integration for multi stage YAML pipelines

### ISSUE THREAD

**Issue by patrickklaeren** [microsoft/azure-pipelines-jira#31]
As per microsoft/azure-pipelines-yaml#455

Is there any mention of when we can expect JIRA traceability for pipelines besides just release pipelines (which have been heavily favoured to be phased out in favour of multi stage YAML pipelines)?

**Comment by AElharouny** [comment]
I'm also interested in JIRA integration with multi stage YAML pipeline

**Comment by spowser** [comment]
Just installed the integration to find out it doesn't work with the suggestion method of developing pipelines. -_-

**Comment by shashban** [comment]
@spowser the integration only works with designer release pipelines. Could you elaborate on that didn't work for you?

**Comment by sefi-jwilliams** [comment]
+1 for support for v2 pipelines

**Comment by spowser** [comment]
@shashban We are using yaml based Azure Pipelines in 100% of our projects.  The documentation seems to push people in the direction of yaml over classic/designer pipelines and if that's the case, support for it seems like it should be prioritized?  This tool would be a huge win for us but I am not going to regress back to classic pipelines for the convenience.

**Comment by tashtechs** [comment]
Any status on this or ETA when YAML Pipelines integrations will be supported?

**Comment by mlstubblefield** [comment]
+1 for this. We're really sad to see it go from the old releases implementation.

**Comment by shashban** [comment]
@spowser @tashtechs @mlstubblefield Thanks for the inputs. 
We have support for YAML pipelines in our backlog. However, we are unable to prioritize this work over other priorities on the core framework of YAML pipelines.
I'll add it to the README that it currently works for classic Release Pipelines only.

**Comment by bernardoflynn** [comment]
everywhere in Azure Devops we're being subtly moved to using yaml and then this kind of thing happens, where something is released that only supports 'the old world' and there is no plan to support where the big ship is moving to.
Is it possible to open this up so that at least the community can add these features?

**Comment by patrickklaeren** [comment]
Any update on this? We're still having to use release pipelines because of this.

**Comment by shashban** [comment]
@vijayma

**Comment by clarkd** [comment]
Any update? The addon actually fails to install in Jira right now too.

**Comment by evertonmc** [comment]
@vijayma  can you give us an roadmap update here?

**Comment by TheSkorm** [comment]
We've recently release this tool that allows similar functionality but as a powershell script that runs as part of deployment steps:

https://github.com/EducationPerfect/azure-jira-update

**Comment by booyaa** [comment]
> We've recently release this tool that allows similar functionality but as a powershell script that runs as part of deployment steps:
> 
> https://github.com/EducationPerfect/azure-jira-update

Going slightly off-topic, but I've just evaluated @TheSkorm 's azure-jira-update tool and there's a good likelihood we'll be using this instead of the Jira app. Nice work!

**Comment by patrickklaeren** [comment]
Dead on arrival https://github.com/microsoft/azure-pipelines-jira/pull/53
