### ISSUE TITLE
How do I use this plugin once it is configured and installed?

### ISSUE THREAD

**Issue by charleshamel73** [microsoft/azure-pipelines-jira#4]
I just installed the plugin and added a project from within JIRA. I also configured the settings to point to one of my projects in Azure.
Seeing as there no documentation, I am assuming I can attach it from "Add Workitems" option in pull request.
Unfortunately when making a pull request and attempting to add a JIRA workitem, I do not find JIRA as a possible option.

How do I use this plugin?

**Comment by shashban** [comment]
Please look at https://github.com/microsoft/azure-pipelines-jira/blob/master/tutorial.md
