### ISSUE TITLE
Unable to Configure Organization

### ISSUE THREAD

**Issue by mirandaposthumus** [microsoft/azure-pipelines-jira#5]
**Describe the bug**
We are unable to configure our Azure DevOps organization because it doesn't appear in the dropdown menu. I thought it was possibly a permissions problem, and so I had the DevOps org owner also try configuring it, but he also did not have the option to add the org.

**To Reproduce**
1. Install Azure Pipelines for Jira in Jira Cloud
2. Click on 'Add Organization'
3. See organization does not appear in the drop down

**Expected behavior**
Populate the dropdown with the correct organizations or provide instructions on how to troubleshoot why an organization may not be showing up.

**Screenshots**
![image](https://user-images.githubusercontent.com/10764202/60281408-82fdd600-98ca-11e9-992a-8ffba1f84c0e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 75.0.3770.100

**Comment by charleshamel73** [comment]
@mirandaposthumus My experience was that it was autolinking the organizations attached to my current logged in microsoft account.
Go to my.visualstudio.com
Login to your microsoft account 
Click your name in the top right side to get to account settings
Verify that your Azure DevOps Organization is present.

**Comment by charleshamel73** [comment]
![image](https://user-images.githubusercontent.com/8124038/60283658-500a1100-98cf-11e9-887c-e612b543e20d.png)

**Comment by charleshamel73** [comment]
See https://docs.microsoft.com/en-us/visualstudio/subscriptions/manage-vs-subscriptions#linking-my-subscription-to-existing-azure-devops-services-or-azure-subscriptions @mirandaposthumus for more information on how to link them

**Comment by mirandaposthumus** [comment]
Thanks for the suggestion @charleshamel73. I tried that, and when I go to my account there is a drop down with 2 different directories, the organization I want to add is in Default Directory, and the organizations the drop down allows me to select from are in the 2nd directory. 

![image](https://user-images.githubusercontent.com/10764202/60346669-3d501480-9981-11e9-85b3-3c4814e479b8.png)

**Comment by jnsn** [comment]
I am experiencing the same thing.

I have a standard Microsoft account which has multiple Azure DevOps organizations. When linking to Jira, I can only select my default organization, not one of the others.

**Comment by aradzevicius** [comment]
Any updates on this?

I can only add organizations where I am the Owner.

**Comment by prativen** [comment]
@mirandaposthumus , @jnsn can you try signing into the right directory in an incognito mode and check if things work?

**Comment by jnsn** [comment]
@prativen Unfortunately that doesn't seem to work. I can only see one DevOps organisation, and not the additional one that was created.

**Comment by JPVenson** [comment]
Any Progress on this i`ve got the same problem but i own 4 Orgs and only one is listed.

**Comment by vithati** [comment]
@JPVenson , Can you try following steps and see it is working for you or not.
1.	Login to jira account. Click ‘Add organization’ button in Azure pipelines app.
2.	It will redirect to login page and after login you will see url in browser similar to https://aexprod....vsaex.visualstudio.com/signup/jira .... (Example:https://aexprodweu1.vsaex.visualstudio.com/signup/jira?acquisitionId=0004e561-f239-4fb0-814e-061c5462baf7&jiraAccountUrl=https%3A%2F2Fmytestaccount.atlassian.net&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1Y2NmZGVlZThiNWFjNDBkY2NhYTJmMDIiLCJxc2giOiJjZmEzNzZmY2RmZWM0MWI1MGNhM2RjNDdjYWQwZDA1MWE0MTk0YjVlY2E1YTM0Mzc5ZWYxYmY0ZTkzZjVjOWNlIiwiaXNzIjoiOGUzM2VlYmYtNjI4Yy0zMWNiLTlhZGQtMGQ2ZGUzNjc5MDg3IiwiY29udGV4dCI6e30sImV4cCI6MTU2NTcwMDI1NiwiaWF0IjoxNTY1Njk5MzU2fQ.IwCVN60j3plOlMKj_-21k4pMO0KNA4viqoOf8c_8n2s )
3.	Replace initial part of url i.e https://aexprodweu1.vsaex.visualstudio.com with https://aex.dev.azure.com
4.	Open this url in private browser.
5.	It will show organization details after login and select required project.

**Comment by JPVenson** [comment]
@vithati wow thank you alot, 4 devlopers have searched for 3 days in our spare time and could not find anything related to that! You saved our day!

**Comment by jnsn** [comment]
Those steps don't seem to work for me. I can still only see one organization.

**Comment by mirandaposthumus** [comment]
@vithati those steps don't work for me either, please advise

**Comment by aarym** [comment]
Same issue and after trying all the above am unable to use company organisation & really wanted to get this integration working to progress to use jira

**Comment by vithati** [comment]
Hi, We have enabled 'directory' selection feature in connection creation page, once you click on the 'Switch directory' it will show different directories in dropdown, you can switch the directory by selecting the directory if you want to configure connection for organization in selected directory. 
![image](https://user-images.githubusercontent.com/19663618/70963720-5ecbc680-20af-11ea-9a90-b7aae869f31a.png)
